### ISSUE TITLE
Add an option exclude files or file types

### ISSUE THREAD

**Issue by adityashah1212** [lee-dohm/tabs-to-spaces#53] opened 2017-09-25 19:45 UTC
When using tabify/untabify on save in  the settings ui, give an option to exclude files or file types. This will handy as Makefiles don't like soft-tabs/spaces

**Comment by lee-dohm** [comment] 2017-09-25 19:54
This is a duplicate of #42. There already is an option for excluding file types, the language-specific configuration system built in to Atom. See #42 for details.

**Closed by lee-dohm** 2017-09-25 19:54 UTC
