### ISSUE TITLE
Space to tabs bug

### ISSUE THREAD

**Issue by alexmoruz** [lee-dohm/tabs-to-spaces#39] opened 2015-11-20 07:48 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [tabs-to-spaces](https://github.com/lee-dohm/tabs-to-spaces) package, v1.0.1

### Stack Trace

Uncaught TypeError: object is not a function

```
At /Users/mac/.atom/packages/tabs-to-spaces/lib/index.coffee:1

TypeError: object is not a function
  at Object.module.exports.loadModule (/Users/mac/.atom/packages/tabs-to-spaces/lib/index.coffee:1:1)
  at atom-workspace.commands.atom.commands.add.tabs-to-spaces:tabify (/Users/mac/.atom/packages/tabs-to-spaces/lib/index.coffee:14:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:20)

```

### Commands

```
     -0:59.2.0 settings-view:open (atom-text-editor.editor.is-focused)
     -0:30.5.0 core:copy (div.package-readme.native-key-bindings)
     -0:29.6.0 pane:show-previous-item (div.package-readme.native-key-bindings)
     -0:29.1.0 key-binding-resolver:toggle (atom-text-editor.editor.is-focused)
     -0:24.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:24.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:22.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:21 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:19.8.0 core:undo (atom-text-editor.editor.mini.is-focused)
     -0:17.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:17.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:15.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:06.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:01.4.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 tabs-to-spaces:tabify (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "material-syntax"
    ]
  },
  "tabs-to-spaces": {}
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.8.0
css-snippets, v0.9.0
highlight-selected, v0.11.1
javascript-snippets, v1.0.0
line-diff-details, v1.1.3
material-syntax, v0.5.0
react, v0.12.10
tabs-to-spaces, v1.0.1

# Dev
No dev packages
```

**Comment by lee-dohm** [comment] 2015-11-20 15:50
This is a duplicate of #38. Unfortunately, the code that I put in to fix this bug isn't loaded yet when the old version of the package is deactivated, so this will continue to occur until people update to v1.0.1 or above.

**Closed by lee-dohm** 2015-11-20 15:50 UTC
